base/urls.py
from django.urls import path
from .views import *
from authentication.views import (
    custom_500_handler,
    custom_error_handler
)

handler500 = 'authentication.views.custom_500_handler'
handler404 = 'authentication.views.custom_error_handler'

urlpatterns = [
    path('bookings/', book_service, name="bookings"),
    path('', home, name="dashboard"),
    path('services/', services, name="services"),
    path('contact/', contact, name="contact"),
    path('about/', about, name="about"),
    path('signinpage/', signin_page, name="signinpage"),
    path('cancel_booking/<str:pk>/', cancel_booking, name="cancel_booking"),
    path('accept_booking/<str:pk>/', accept_booking, name="accept_booking"),
    path('complete_booking/<str:pk>/',
         complete_booking, name="complete_booking"),
]

bookaservice/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import (
    custom_500_handler,
    custom_error_handler
)

handler500 = 'authentication.views.custom_500_handler'
handler404 = 'authentication.views.custom_error_handler'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('base.urls')),
    path('', include('client.urls')),
    path('', include('business.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager

customer_types = (
    (1, "Customer"),
    (2, "Business"),
)

# Diesel, Petrol, Hybrid, Electric
FUEL_TYPES = (
    ("diesel", "Diesel"),
    ("petrol", "Petrol"),
    ("hybrid", "Hybrid"),
    ("electric", "Electric"),
)


class Locations(models.Model):
    Malta_Locations = [
        ('Attard', 'Attard'),
        ('Ħal-Balzan', 'Ħal-Balzan'),
        ('Il-Bidnija', 'Il-Bidnija'),
        ('Il-Birgu', 'Il-Birgu'),
        ('Birkirkara', 'Birkirkara'),
        ('Birżebbuġa', 'Birżebbuġa'),
        ('Bormla', 'Bormla'),
        ('Ħad-Dingli', 'Ħad-Dingli'),
        ('Il-Fgura', 'Il-Fgura'),
        ('Il-Furjana', 'Il-Furjana'),
        ('Ħal Għargħur', 'Ħal Għargħur'),
        ('Ħal Għaxaq', 'Ħal Għaxaq'),
        ('Il-Gudja', 'Il-Gudja'),
        ('Il-Gżira', 'Il-Gżira'),
        ('Il-Ħamrun', 'Il-Ħamrun'),
        ('L-Iklin', 'L-Iklin'),
        ('Il-Kalkara', 'Il-Kalkara'),
        ('Ħal Kirkop', 'Ħal Kirkop'),
        ('Ħal Lija', 'Ħal Lija'),
        ('Ħal Luqa', 'Ħal Luqa'),
        ('Il-Marsa', 'Il-Marsa'),
        ('Marsaskala', 'Marsaskala'),
        ('Marsaxlokk', 'Marsaxlokk'),
        ('L-Imdina', 'L-Imdina'),
        ('Il-Mellieħa', 'Il-Mellieħa'),
        ('L-Imġarr', 'L-Imġarr'),
        ('Il-Mosta', 'Il-Mosta'),
        ('L-Imqabba', 'L-Imqabba'),
        ('L-Imsida', 'L-Imsida'),
        ('L-Imtarfa', 'L-Imtarfa'),
        ('In-Naxxar', 'In-Naxxar'),
        ('Raħal Ġdid', 'Raħal Ġdid'),
        ('Pembroke', 'Pembroke'),
        ('Tal-Pietà', 'Tal-Pietà'),
        ('Ħal Qormi', 'Ħal Qormi'),
        ('Il-Qrendi', 'Il-Qrendi'),
        ('Ir-Rabat Malta', 'Ir-Rabat Malta'),
        ('Ħal Safi', 'Ħal Safi'),
        ('San Ġwann', 'San Ġwann'),
        ('Santa Luċija', 'Santa Luċija'),
        ('Santa Venera', 'Santa Venera'),
        ('L-Isla', 'L-Isla'),
        ('Is-Siġġiewi', 'Is-Siġġiewi'),
        ('Tas-Sliema', 'Tas-Sliema'),
        ('San Ġiljan', 'San Ġiljan'),
        ('San Pawl il-Baħar', 'San Pawl il-Baħar'),
        ('Is-Swieqi', 'Is-Swieqi'),
        ('Ħal Tarxien', 'Ħal Tarxien'),
        ('Ta Xbiex', 'Ta Xbiex'),
        ('Valletta', 'Valletta'),
        ('Ix-Xgħajra', 'Ix-Xgħajra'),
        ('Ħaż-Żabbar', 'Ħaż-Żabbar'),
        ('Ħaż-Żebbuġ', 'Ħaż-Żebbuġ'),
        ('Iż-Żejtun', 'Iż-Żejtun'),
        ('Iż-Żurrieq', 'Iż-Żurrieq'),
        ('Il-Fontana', 'Il-Fontana'),
        ('Għajnsiele', 'Għajnsiele'),
        ('L-Għarb', 'L-Għarb'),
        ('L-Għasri', 'L-Għasri'),
        ('Ta Kerċem', 'Ta Kerċem'),
        ('Il-Munxar', 'Il-Munxar'),
        ('Ix-Xlendi', 'Ix-Xlendi'),
        ('In-Nadur', 'In-Nadur'),
        ('Il-Qala', 'Il-Qala'),
        ('Ir-Raba', 'Ir-Raba'),
        ('San Lawrenz', 'San Lawrenz'),
        ('Ta Sannat', 'Ta Sannat'),
        ('Ix-Xagħra', 'Ix-Xagħra'),
        ('Ix-Xewkija', 'Ix-Xewkija'),
        ('Iż-Żebbuġ Gozo', 'Iż-Żebbuġ Gozo'),
        ('Marsalforn', 'Marsalforn'),
    ]


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    objects = UserManager()

    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"

    def is_customer(self):
        return Customer.objects.filter(user=self).exists()

    def is_business_owner(self):
        return Business.objects.filter(user=self).exists()


class Customer(models.Model):
    user = models.OneToOneField(
        User,
        related_name="customer",
        on_delete=models.CASCADE)
    Location = models.CharField(
        max_length=50,
        choices=Locations.Malta_Locations,
        blank=False,
        null=False)
    Mobile = models.CharField(max_length=8, blank=False)
    Vat_Number = models.CharField(max_length=11, blank=True, null=True)
    ID_number = models.CharField(max_length=10, blank=False, unique=True)
    Address = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return self.user.email


class Car(models.Model):
    owner = models.ForeignKey(
        Customer,
        related_name="cars",
        on_delete=models.CASCADE)
    Brand = models.CharField(max_length=200)
    Model = models.CharField(max_length=200, blank=False)
    Fuel_Type = models.CharField(
        blank=False,
        choices=FUEL_TYPES,
        default="diesel",
        max_length=20)
    VIN = models.CharField(max_length=200, blank=False)
    NumPlate = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return self.NumPlate


class Business(models.Model):
    user = models.OneToOneField(
        User,
        related_name="business",
        on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=False)
    Location = models.CharField(
        max_length=50,
        choices=Locations.Malta_Locations,
        blank=False,
        null=False)
    Mobile = models.CharField(max_length=8, blank=False)
    Vat_Number = models.CharField(max_length=11, unique=True)
    Address = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=200)
    provider = models.ForeignKey(
        Business,
        on_delete=models.CASCADE,
        related_name="services")

    def __str__(self):
        return self.name


class BookService(models.Model):
    client = models.ForeignKey(
        Customer,
        related_name="bookings",
        on_delete=models.CASCADE)
    car = models.ForeignKey(
        Car,
        related_name="bookings",
        on_delete=models.CASCADE)
    service = models.ForeignKey(
        Service,
        related_name="bookings",
        on_delete=models.CASCADE)
    details = models.TextField(null=True, blank=True)
    deliver_date = models.DateField()
    acceptation = models.BooleanField(default=False)
    cancelled = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)

    class Meta:
        ordering = ["completed"]

    def __str__(self):
        return self.service.name

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from accounts.models import Service, Business, BookService, Car, Customer
from datetime import datetime


def home(request):
    return render(request, "index.html")


def contact(request):
    return render(request, 'contact.html')


@login_required
def book_service(request):
    """These views collectively handle various aspects of the application,
    including booking services, managing bookings, handling errors, and
    rendering different pages."""
    is_user_customer = Customer.objects.filter(user=request.user).exists()
    if is_user_customer:
        if request.method == "POST":
            data = request.POST
            car = data.get("car")
            service = data.get("service")
            details = data.get("details")
            date = data.get("date")
            deliver_date = datetime.strptime(date, "%m/%d/%Y")

            BookService.objects.create(
                client=request.user.customer,
                car=Car.objects.get(pk=int(car)),
                service=Service.objects.get(pk=int(service)),
                details=details,
                deliver_date=deliver_date
            )

        businesses = Business.objects.all()
        services_available = Service.objects.all()
        cars = request.user.customer.cars.all()
        bookings = request.user.customer.bookings.all()
        print(bookings.filter(acceptation=True).filter())
        context = {
            "providers": businesses,
            "services": services_available,
            "cars": cars,
            "bookings": bookings,
            'is_user_customer': is_user_customer
        }

    else:

        bookings = BookService.objects.filter(
            service__provider__user=request.user)
        pending_bookings = bookings.filter(cancelled=False)
        completed_bookings = bookings.filter(completed=True)
        print(f"Pending bookings are {pending_bookings}")

        context = {
            "bookings": bookings.filter(
                acceptation=True).filter(
                completed=False),
            'pending_bookings': pending_bookings.filter(
                completed=False).filter(
                    acceptation=False),
            'is_user_customer': is_user_customer,
            'completed_bookings': completed_bookings,
            'rejected_bookings': bookings.filter(
                cancelled=True)}
    return render(request, "dashboard.html", context)


def services(request):
    if request.method == "POST":
        pass
    return render(request, "service.html")


def about(request):
    return render(request, 'about.html')


def signin_page(request):
    return render(request, 'signinpage.html')


def custom_500_handler(request, exception=None):
    return render(request, 'page_404.html', status=500)


def custom_error_handler(request, exception=None):
    if exception is None:
        return render(request, 'page_404.html', status=404)
    else:
        return render(request, 'page_404.html', status=404)


def cancel_booking(request, pk):
    booking = BookService.objects.get(pk=pk)
    booking.cancelled = True
    booking.save()
    return redirect("bookings")


def accept_booking(request, pk):
    booking = BookService.objects.get(pk=pk)
    booking.acceptation = True
    booking.save()
    return redirect("bookings")


def complete_booking(request, pk):
    booking = BookService.objects.get(pk=pk)
    booking.completed = True
    booking.save()
    return redirect("bookings")

templates/bookings.html
{% extends "base.html" %} {% block content %}

<!-- About Start -->
{% if is_user_customer %}

<div class="container-xxl py-5">
  <div class="container text-center">
    <h1 class="mt-5 mb-2">Booked Services</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Service Provider</th>
          <th>Service</th>
          <th>Car</th>
          <th>Deliverable Date</th>
        </tr>
      </thead>
      <tbody>
        {% for booking in accepted_bookings %}

        <tr>
          <td>{{ booking.service.provider }}</td>
          <td>{{ booking.service.name }}</td>
          <td>{{ booking.car.Model}} -- {{ booking.car.NumPlate }}</td>
          <td>{{ booking.deliver_date}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <h1 class="mt-5 mb-2">Pending Requests</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Service Provider</th>
          <th>Service</th>
          <th>Car</th>
          <th>Deliverable Date</th>
        </tr>
      </thead>
      <tbody>
        {% for booking in rejected_bookings %}

        <tr>
          <td>{{ booking.service.provider }}</td>
          <td>{{ booking.service.name }}</td>
          <td>{{ booking.car.Model}} -- {{ booking.car.NumPlate }}</td>
          <td>{{ booking.deliver_date}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div class="container-xxl py-5">
  <div class="container">
    <div class="container booking">
      <div class="row gx-5">
        <div class="col-lg-6 py-5">
          <div class="py-5">
            <h1 class="text-white mb-4">
              Certified and Award Winning Car Repair Service Provider
            </h1>
            <p class="text-white mb-0">
              Eirmod sed tempor lorem ut dolores. Aliquyam sit sadipscing kasd
              ipsum. Dolor ea et dolore et at sea ea at dolor, justo ipsum duo
              rebum sea invidunt voluptua. Eos vero eos vero ea et dolore eirmod
              et. Dolores diam duo invidunt lorem. Elitr ut dolores magna sit.
              Sea dolore sanctus sed et. Takimata takimata sanctus sed.
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="">
      <div
        class="m-5 p-5 bg-primary h-100 d-flex flex-column justify-content-center text-center p-5 wow zoomIn"
        data-wow-delay="0.6s"
      >
        <h1 class="text-white mb-4">Book For A Service</h1>
        <form action="{% url 'bookings' %}" method="post">
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-12 col-sm-6">
              <select
                name="provider"
                class="form-select border-0"
                style="height: 55px"
                id="provider"
              >
                <option selected>Select A Service Provider</option>
                {% for provider in providers %}
                <option value="{{ provider.id }}">{{ provider.name }}</option>
                {% endfor %}
              </select>
            </div>

            <div class="col-12 col-sm-6">
              <select
                class="form-select border-0"
                name="service"
                id="service"
                style="height: 55px"
              >
                <option selected>Select A Service</option>
                {% for service in services %}
                <option
                  value="{{ service.id }}"
                  data-provider="{{ service.provider.id }}"
                >
                  {{ service.name }}
                </option>
                {% endfor %}
              </select>
            </div>

            <div class="col-12 col-sm-6">
              <select
                name="car"
                class="form-select border-0"
                style="height: 55px"
                id="car"
              >
                <option selected>Select Your Car</option>
                {% for car in cars %}
                <option value="{{ car.id }}">
                  {{ car.Model }} - {{ car.NumPlate }}
                </option>
                {% endfor %}
              </select>
            </div>

            <div class="col-12 col-sm-6">
              <div class="date" id="date1" data-target-input="nearest">
                <input
                  type="text"
                  name="date"
                  class="form-control border-0 datetimepicker-input"
                  placeholder="Service Date"
                  data-target="#date1"
                  data-toggle="datetimepicker"
                  style="height: 55px"
                />
              </div>
            </div>
            <div class="col-12">
              <textarea
                class="form-control border-0"
                placeholder="Special Request"
                name="details"
              ></textarea>
            </div>
            <div class="col-12">
              <button class="btn btn-secondary w-100 py-3" type="submit">
                Book Now
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- About End -->
  {% endif %} {% if not is_user_customer %}

  <div class="container-xxl py-5">
    <div class="container text-center">
      <h1 class="mt-5 mb-2">Booked Services</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Service Provider</th>
            <th>Service</th>
            <th>Car</th>
            <th>Deliverable Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for booking in accepted_bookings %}

          <tr>
            <td>{{ booking.service.provider }}</td>
            <td>{{ booking.service.name }}</td>
            <td>{{ booking.car.Model}} -- {{ booking.car.NumPlate }}</td>
            <td>{{ booking.deliver_date}}</td>
            <td>
              <form action="{% url 'bookings' %}" method="post">
                {% csrf_token %}
                <input type="text" name="id" value="{{booking.id}}" hidden />
                <button type="submit" class="btn btn-primary">Reject</button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <h1 class="mt-5 mb-2">Pending Requests</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Service Provider</th>
            <th>Service</th>
            <th>Car</th>
            <th>Deliverable Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for booking in rejected_bookings %}

          <tr>
            <td>{{ booking.service.provider }}</td>
            <td>{{ booking.service.name }}</td>
            <td>{{ booking.car.Model}} -- {{ booking.car.NumPlate }}</td>
            <td>{{ booking.deliver_date}}</td>
            <td>
              <form action="{% url 'bookings' %}" method="post">
                {% csrf_token %}
                <input type="text" name="id" value="{{booking.id}}" hidden="" />
                <button type="submit" class="btn btn-info text-white">
                  Accept
                </button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="container-xxl py-5">{% endif %} {% endblock %}</div>
</div>

templates/business_profile_update.html
{% extends "base.html" %}
{% block content %}

 <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="text-primary text-uppercase">// Profile Update //</h6>
            </div>
            <div class="row g-4 table-responsive">

                 <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-primary">Save</button>
                </form>

            </div>

        </div>
    </div>
    <!-- Contact End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

{% endblock %}

templates/client_profile.html
{% extends "base.html" %}
{% block content %}
 <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="text-primary text-uppercase">// Settings //</h6>
            </div>

            <div class="profile">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center">Profile Settings</h4>
                        <p class="card-text"><strong>First Name</strong><br> {{ user.first_name }}</p>
                        <p class="card-text"><strong>Last Name</strong> <br>{{ user.last_name }}</p>
                        <p class="card-text"><strong>Email Address</strong> <br>{{ user.email }}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-warning " href="{% url 'edit_profile' %}">Edit Details</a>
                        <a href="{% url 'password_update' %}" class="btn btn-info text-light" >Update Password</a>
                    </div>
                </div>
            </div>


            <div class="profile">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center">Customer Settings</h4>
                        <p class="card-text"><strong>Id Number</strong><br> {{ user.customer.ID_number }}</p>
                        <p class="card-text"><strong>Mobile</strong> <br>{{ user.customer.Mobile }}</p>
                        <p class="card-text"><strong>VAT Number</strong> <br>{{ user.customer.Vat_Number }}</p>
                        <p class="card-text"><strong>Location</strong> <br>{{ user.customer.get_Location_display }}</p>
                        <p class="card-text"><strong>Address</strong><br> {{ user.customer.Address }}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-warning " href="{% url 'customer_profile_update' pk=user.customer.pk %}">Edit Details</a>
                        <button class="btn btn-danger" id="deleteAccountButton" data-toggle="modal" data-target="#confirmDeleteModal">Delete Account</button>
                    </div>
                </div>
            </div>



            <!-- Confirmation Modal -->
            <div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Deletion</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete your account?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <button type="button" class="btn btn-danger" id="confirmDeleteButton">Sure</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- Contact End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

    <script>
        document.getElementById("confirmDeleteButton").addEventListener("click", function () {
            // Redirect to the delete_account URL when "Sure" is clicked
            window.location.href = "{% url 'delete_account' %}";
        });
    </script>
{% endblock %}

templates/client_profile_update.html
{% extends "base.html" %}
{% block content %}

 <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="text-primary text-uppercase">// Profile Update //</h6>
            </div>
            <div class="row g-4 table-responsive">

                 <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-primary">Save</button>
                </form>

            </div>

        </div>
    </div>
    <!-- Contact End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

{% endblock %}

templates/page_404.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>404 Error Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>


<section class="page_404">
	<div class="container">
		<div class="row">	
		<div class="col-sm-12 ">
		<div class="col-sm-10 col-sm-offset-1  text-center">
		<div class="four_zero_four_bg">
			<h1 class="text-center ">404</h1>
		
		
		</div>
		
		<div class="contant_box_404">
		<h3 class="h2">
		Look like you're lost
		</h3>
		
		<p>the page you are looking for not avaible!</p>
		
		<a href="{% url 'dashboard' %}" class="link_404">Go to Home</a>
	</div>
		</div>
		</div>
		</div>
	</div>
</section>

templates/signin.html
{% extends "base.html" %} {% block content %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <title>signin</title>
  </head>
  <body>
    <div class="containers">
        {% if messages %}
            <div class="alert alert-danger">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

      <div class="login">
        <form action="{% url 'login' %}" method="post" class="containers">
            {% csrf_token %}
          <h1 class="text-primary">Log in</h1>
          <input name="email" type="email" placeholder="Email" />
          <input name="password" type="password" placeholder="Password" /><br />
          <input type="checkbox" /><span>Remember me</span>
          <a href="#">Forgot password?</a>
          <button>log in</button>
          <hr />
          <p>Or Connect With</p>
          <hr />

          <div class="clearfix"></div>
          <span class="copyright">&copy;2023</span>
        </form>
      </div>
      <div class="register">
        <div class="containers">
          <i class="fas fa-user-plus fa-5x"></i>
          <h2 class="text-info">Hello,friend!</h2>
          <p>Enter your personal details and start journey with us</p>
          <a class="button" href="{% url 'signinpage' %}"
            >Register <i class="fas fa-arrow-circle-right"></i
          ></a>
        </div>
      </div>
    </div>
  </body>
</html>

{% endblock %}

templates/user_profile_update.html
{% extends "base.html" %}
{% block content %}

 <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="text-primary text-uppercase">// Profile Update //</h6>
            </div>
            <div class="row g-4 table-responsive">

                 <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-primary">Save</button>
                </form>

            </div>

        </div>
    </div>
    <!-- Contact End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

{% endblock %}